### PR TITLE
Draft link generation logic for Redcap, XNAT

### PR DESCRIPTION
**Pull request by shippy**
This is a work in progress. `links.yml` should probably be moved to the `operations` folder/repo; the config should probably be loaded through `sibispy.Session`. @kipohl, can I ask you for some integration advice?

This PR will be ready to merge when:

* [ ] A good way to store/load configuration has been determined & implemented,
* [ ] There's a straightforward way to invoke it from the logger.

### CODE REVIEW

**Comment by kipohl** [comment]
+  base_url: "https://ncanda.sri.com/redcap/redcap_v8.4.0/DataEntry/index.php?pid=20"
should not be explicitly defined for each project but be defined through the given definition in sibis_general_config.yml and as part of a function sibispy/session.py

the same for 
+  dashboard_url:

**Comment by kipohl** [comment]
this is with respect to links.yml  the rest of the script should most likely be put into 
sibis_sys_config.yml

**Comment by shippy** [comment]
The point of entry: [sibislogger.py#create_log](https://github.com/sibis-platform/sibispy/blob/master/sibislogger.py#L39)

**Comment by shippy** [comment]
To do:

- [ ] Move config into `operations` / use existing config where appropriate
- [ ] Integrate into sibislogger

**Pull request closed without merging**
