### PR TITLE
added ignoring of excluded visits/subjects in export measures check for ncanda

### PR DESCRIPTION
**Pull request by jodahoney**
Now script will no longer check for export_measures log files in directories where the visit is marked as excluded or a subject is marked as excluded in redcap.

### CODE REVIEW

**Comment by kipohl** [comment]
@jodahoney any reason why you did not check the status from redcap directly as we normally do ? we normally do not rely on the csv files for decision making as they could be outdated

**Comment by jodahoney** [comment]
@kipohl which status? For the visit ignore and subject exception I am pulling from redcap directly via session export_measures function

**Comment by kipohl** [comment]
if visit/subject  is ignored - you look at csv file

**Comment by jodahoney** [comment]
Oh I see, yes I grab the participant id from demographics in the loop so map the NCANDA S number to redcap record, I could eliminate that step and just grab the pid from the redcap export measures step. Will update

**Comment by jodahoney** [comment]
@kipohl I remember why I had to pull from demographics csv, I needed a way to reconcile between NCANDA S number (sid) and participant study id (pid) to determine if the current path of the visit is one to be excluded. Redcap orients around PID and cases is based on SID. However, getting SID from Redcap is not reliable because the only place I know of to grab it is from the mri xnat summary report, which wouldn't exist for a skipped visit. 
Therefore I grab the PID of the current visit I am in to get the PID -> SID mapping. If the demographics file doesn't exist then I add it to the list of  visits to be investigated since a measures directory without demographics needs to be fixed anyways.
Does that make sense? Can meet about it

**Pull request merged**
