### PR TITLE
Adding a simple pytest and some configuration.

### PR DESCRIPTION
**Pull request by jimklo**
This is a companion PR to sibis-platform/sibis-docker#23.

This adds a relatively harmless test using pytest.

Currently you will need to run this like to prevent autodiscovery:
```
cd tests
pytest test_github.py
```

### CODE REVIEW

**Comment by jimklo** [comment]
Notes from meeting w/ @kipohl:

@jimklo will:
- [ ] rename `test_github.py` to something like `test_post_to_github_unit.py` or something more distinctive.
- [ ] move the data for the test github labels into ncanda_operations into a test config YAML file.
- [ ] move test data from sysconfig into test config YAML and update test files appropriately (This might need to be in a separate issue.)

**Comment by kipohl** [comment]
jim - please change label of pull request when it is ready to be merged

**Comment by jimklo** [comment]
@kipohl This should be ready... note that this depends upon sibis-platform/ncanda-operations#75 in order to work correctly.

Also if the pipeline-system docker images haven't been rebuilt, along with derivative images, pytest won't be available for these to run.

**Comment by kipohl** [comment]
@shippy can you update the production according to jim's note ?

**Pull request merged**
