### PR TITLE
Adding slog call for duplicate variables

### PR DESCRIPTION
**Pull request by gcyoung1**
Continued from  #75

### CODE REVIEW

**Comment by gcyoung1** [comment]
Still need to test. Currently held up by permission errors pulling from sibispy.

**Comment by gcyoung1** [comment]
```
ncanda@pipeline-back[pipeline_back_1]:/sibis-software/python-packages/sibispy/cmds (bug/duplicate_variable_in_txt)$ python /sibis-software/ncanda-data-integration/scripts/redcap/export_measures --subject D-00312-M-9 -v /fs/ncanda-share/cases -p
================================
== Setting up posting to GitHub 
Setting up GitHub...
Parsing config: None
Using Personal Access Token to authenticate.
Connected to GitHub
... ready!
Found label: [Label(name="export_measures")]
== Posting to GitHub is ready 
================================
INFO: Modified link for A-00082-F-3 from NCANDA_S01168 to NCANDA_S00617 !
INFO: Modified link for A-00129-M-1 from NCANDA_S01063 to NCANDA_S00776 !
INFO: Ignoring link B-00359-F-1 to NCANDA_S01104 as already already linked to NCANDA_S00555 !
INFO: Ignoring link B-00368-M-9 to NCANDA_S01107 as already already linked to NCANDA_S00480 !
INFO: Modified link for B-00381-F-2 from NCANDA_S01091 to NCANDA_S00558 !
INFO: Ignoring link B-80556-F-6 to NCANDA_S01024 as already already linked to NCANDA_S01001 !
INFO: Modified link for C-70087-M-8 from NCANDA_S01166 to NCANDA_S00548 !
INFO: Ignoring link C-70158-F-4 to NCANDA_S01164 as already already linked to NCANDA_S00693 !
INFO: Ignoring link C-70165-F-9 to NCANDA_S01058 as already already linked to NCANDA_S00747 !
INFO: Ignoring link D-00094-M-5 to NCANDA_S01011 as already already linked to NCANDA_S00270 !
INFO: Modified link for D-00133-F-0 from NCANDA_S01099 to NCANDA_S00425 !
INFO: Modified link for D-00141-M-9 from NCANDA_S01147 to NCANDA_S00292 !
INFO: Ignoring link D-00159-F-2 to NCANDA_S01100 as already already linked to NCANDA_S00327 !
INFO: Modified link for E-00018-F-2 from NCANDA_S01165 to NCANDA_S00033 !
INFO: Modified link for E-00051-M-9 from NCANDA_S01031 to NCANDA_S00060 !
INFO: Ignoring link E-00084-F-7 to NCANDA_S01035 as already already linked to NCANDA_S00142 !
INFO: Modified link for E-00090-F-1 from NCANDA_S01057 to NCANDA_S00129 !
INFO: Modified link for E-00186-M-0 from NCANDA_S01094 to NCANDA_S00193 !
INFO: Modified link for E-00348-F-2 from NCANDA_S01105 to NCANDA_S00446 !
INFO: Ignoring link E-00445-M-9 to NCANDA_S01167 as already already linked to NCANDA_S00442 !
INFO: Ignoring link E-00649-M-2 to NCANDA_S01078 as already already linked to NCANDA_S00818 !
INFO: Ignoring link E-00879-M-8 to NCANDA_S01076 as already already linked to NCANDA_S00672 !
INFO: Modified link for E-00880-M-1 from NCANDA_S01101 to NCANDA_S00662 !
INFO: Modified link for X-99997-F-9 from NCANDA_S00240 to NCANDA_S00157 !
INFO: Ignoring link X-99997-F-9 to NCANDA_S00212 as already already linked to NCANDA_S00157 !
INFO: Ignoring link X-99997-F-9 to NCANDA_S00201 as already already linked to NCANDA_S00157 !
INFO: Ignoring link X-99997-F-9 to NCANDA_S01018 as already already linked to NCANDA_S00157 !
INFO: Modified link for X-99998-M-9 from NCANDA_S00208 to NCANDA_S00200 !
INFO: Ignoring link X-99998-M-9 to NCANDA_S00765 as already already linked to NCANDA_S00200 !
INFO: Modified link for X-99998-M-9 from NCANDA_S00200 to NCANDA_S00147 !
INFO: Ignoring link X-99998-M-9 to NCANDA_S00158 as already already linked to NCANDA_S00147 !
INFO: Ignoring link X-99999-F-9 to NCANDA_S00040 as already already linked to NCANDA_S00030 !
INFO: Ignoring link X-99999-F-9 to NCANDA_S00053 as already already linked to NCANDA_S00030 !
INFO: Modified link for X-99999-F-9 from NCANDA_S00030 to NCANDA_S00023 !
INFO: Ignoring link X-99999-F-9 to NCANDA_S00035 as already already linked to NCANDA_S00023 !
Exporting 16 REDCap records.
Posting redcap_to_casesdir.export_subject_form ERROR: duplicate variable 'youthreport1_year' in youthreport1_demographics.
Checking for issue: redcap_to_casesdir.export_subject_form, ERROR: duplicate variable 'youthreport1_year' in youthreport1_demographics.
Issue does not exist.
Created issue... See: https://api.github.com/repos/sibis-platform/ncanda-operations/issues/11558
Posting redcap_to_casesdir.export_subject_form ERROR: duplicate variable 'youthreport1_year' in youthreport1_demographics.
Checking for issue: redcap_to_casesdir.export_subject_form, ERROR: duplicate variable 'youthreport1_year' in youthreport1_demographics.
Open issue already exists... See: https://api.github.com/repos/sibis-platform/ncanda-operations/issues/11558
Posting redcap_to_casesdir.export_subject_form ERROR: duplicate variable 'youthreport1_year' in youthreport1_demographics.
Checking for issue: redcap_to_casesdir.export_subject_form, ERROR: duplicate variable 'youthreport1_year' in youthreport1_demographics.
^CTraceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 377, in _make_request
    httplib_response = conn.getresponse(buffering=True)
TypeError: getresponse() got an unexpected keyword argument 'buffering'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/sibis-software/ncanda-data-integration/scripts/redcap/export_measures", line 364, in <module>
    red2cas.export_subject_all_forms(redcap_project,
  File "/sibis-software/python-packages/sibispy/redcap_to_casesdir.py", line 559, in export_subject_all_forms
    self.export_subject_form(export_name, subject, subject_code, arm_code, visit_code, all_records, measures_dir, verbose)
  File "/sibis-software/python-packages/sibispy/redcap_to_casesdir.py", line 472, in export_subject_form
    slog.info("redcap_to_casesdir.export_subject_form", f"ERROR: duplicate variable '{output_field}' in {export_name}.")
  File "/sibis-software/python-packages/sibispy/sibislogger.py", line 218, in info
    return log.info(uid,message,**kwargs)
  File "/sibis-software/python-packages/sibispy/sibislogger.py", line 85, in info
    return pig.create_issues_from_list(self.postGithubRepo, self.postGithubTitle, self.postGithubLabel, [jlog],self.verbose)
  File "/sibis-software/python-packages/sibispy/post_issues_to_github.py", line 250, in create_issues_from_list
    open_issue = is_open_issue(repo, subject, label = label, verbose=verbose)
  File "/sibis-software/python-packages/sibispy/post_issues_to_github.py", line 152, in is_open_issue
    issue = get_issue(repo, subject, labelList=label, verbose=verbose)
  File "/sibis-software/python-packages/sibispy/post_issues_to_github.py", line 134, in get_issue
    for issue in issueList: 
  File "/usr/local/lib/python3.8/site-packages/github/PaginatedList.py", line 56, in __iter__
    newElements = self._grow()
  File "/usr/local/lib/python3.8/site-packages/github/PaginatedList.py", line 67, in _grow
    newElements = self._fetchNextPage()
  File "/usr/local/lib/python3.8/site-packages/github/PaginatedList.py", line 199, in _fetchNextPage
    headers, data = self.__requester.requestJsonAndCheck(
  File "/usr/local/lib/python3.8/site-packages/github/Requester.py", line 354, in requestJsonAndCheck
    *self.requestJson(
  File "/usr/local/lib/python3.8/site-packages/github/Requester.py", line 454, in requestJson
    return self.__requestEncode(cnx, verb, url, parameters, headers, input, encode)
  File "/usr/local/lib/python3.8/site-packages/github/Requester.py", line 528, in __requestEncode
    status, responseHeaders, output = self.__requestRaw(
  File "/usr/local/lib/python3.8/site-packages/github/Requester.py", line 555, in __requestRaw
    response = cnx.getresponse()
  File "/usr/local/lib/python3.8/site-packages/github/Requester.py", line 127, in getresponse
    r = verb(
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 597, in urlopen
    httplib_response = self._make_request(conn, method, url,
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/local/lib/python3.8/http/client.py", line 1347, in getresponse
    response.begin()
  File "/usr/local/lib/python3.8/http/client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "/usr/local/lib/python3.8/http/client.py", line 268, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/local/lib/python3.8/socket.py", line 669, in readinto
    return self._sock.recv_into(b)
  File "/usr/local/lib/python3.8/ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/local/lib/python3.8/ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
KeyboardInterrupt
^C
```

**Comment by kipohl** [comment]
please show that it is now working

**Comment by kipohl** [comment]
what the error message is when it has double entries

**Comment by kipohl** [comment]
@gcyoung1

**Comment by gcyoung1** [comment]
@kipohl the comment above is a test run. This is the issue it created: [#11558](https://github.com/sibis-platform/ncanda-operations/issues/11558)

**Pull request merged**
